# Shared constants for the D&D AI Assistant

EDITION_2014 = "2014 Edition"
EDITION_2024 = "2024 Revision (5.5e)"
EDITIONS = [EDITION_2014, EDITION_2024]

GENDERS = ["Male", "Female", "Non-binary", "Other"]

ALIGNMENTS = [
    "Lawful Good",
    "Neutral Good",
    "Chaotic Good",
    "Lawful Neutral",
    "True Neutral",
    "Chaotic Neutral",
    "Lawful Evil",
    "Neutral Evil",
    "Chaotic Evil",
]

# ==========================================
# 2014 Ruleset (5e) - Expanded with XGtE, TCoE, etc.
# ==========================================
RACES_2014 = [
    "Human",
    "Elf",
    "Dwarf",
    "Halfling",
    "Dragonborn",
    "Tiefling",
    "Half-Orc",
    "Gnome",
    "Half-Elf",
    "Aasimar",
    "Firbolg",
    "Goliath",
    "Kenku",
    "Lizardfolk",
    "Tabaxi",
    "Triton",
    "Bugbear",
    "Goblin",
    "Hobgoblin",
    "Kobold",
    "Orc",
    "Yuan-ti Pureblood",
    "Tortle",
    "Changeling",
    "Kalashtar",
    "Shifter",
    "Warforged",
    "Centaur",
    "Loxodon",
    "Minotaur",
    "Simic Hybrid",
    "Vedalken",
    "Satyr",
    "Leonin",
    "Fairy",
    "Harengon",
    "Owlin",
]

CLASSES_2014 = [
    "Artificer",
    "Barbarian",
    "Bard",
    "Cleric",
    "Druid",
    "Fighter",
    "Monk",
    "Paladin",
    "Ranger",
    "Rogue",
    "Sorcerer",
    "Warlock",
    "Wizard",
]

BACKGROUNDS_2014 = [
    "Acolyte",
    "Charlatan",
    "Criminal",
    "Entertainer",
    "Folk Hero",
    "Guild Artisan",
    "Hermit",
    "Noble",
    "Outlander",
    "Sage",
    "Sailor",
    "Soldier",
    "Urchin",
    "Anthropologist",
    "Archaeologist",
    "Athlete",
    "City Watch",
    "Clan Crafter",
    "Cloistered Scholar",
    "Courtier",
    "Faction Agent",
    "Far Traveler",
    "Fisher",
    "Gladiator",
    "Inheritor",
    "Knight",
    "Knight of the Order",
    "Marine",
    "Mercenary Veteran",
    "Urban Bounty Hunter",
    "Uthgardt Tribe Member",
    "Waterdhavian Noble",
]

SUBCLASSES_2014 = {
    "Artificer": ["Alchemist", "Armorer", "Artillerist", "Battle Smith"],
    "Barbarian": [
        "Path of the Berserker",
        "Path of the Totem Warrior",
        "Path of the Ancestral Guardian",
        "Path of the Storm Herald",
        "Path of the Zealot",
        "Path of the Beast",
        "Path of Wild Magic",
    ],
    "Bard": [
        "College of Lore",
        "College of Valor",
        "College of Glamour",
        "College of Swords",
        "College of Whispers",
        "College of Creation",
        "College of Eloquence",
        "College of Spirits",
    ],
    "Cleric": [
        "Knowledge Domain",
        "Life Domain",
        "Light Domain",
        "Nature Domain",
        "Tempest Domain",
        "Trickery Domain",
        "War Domain",
        "Forge Domain",
        "Grave Domain",
        "Order Domain",
        "Peace Domain",
        "Twilight Domain",
        "Arcana Domain",
        "Death Domain",
    ],
    "Druid": [
        "Circle of the Land",
        "Circle of the Moon",
        "Circle of Dreams",
        "Circle of the Shepherd",
        "Circle of Spores",
        "Circle of Stars",
        "Circle of Wildfire",
    ],
    "Fighter": [
        "Champion",
        "Battle Master",
        "Eldritch Knight",
        "Arcane Archer",
        "Cavalier",
        "Samurai",
        "Echo Knight",
        "Psi Warrior",
        "Rune Knight",
    ],
    "Monk": [
        "Way of the Open Hand",
        "Way of Shadow",
        "Way of the Four Elements",
        "Way of the Long Death",
        "Way of the Sun Soul",
        "Way of the Drunken Master",
        "Way of the Kensei",
        "Way of the Astral Self",
        "Way of the Mercy",
        "Way of the Ascendant Dragon",
    ],
    "Paladin": [
        "Oath of Devotion",
        "Oath of the Ancients",
        "Oath of Vengeance",
        "Oath of the Crown",
        "Oath of Conquest",
        "Oath of Redemption",
        "Oath of Glory",
        "Oath of the Watchers",
        "Oathbreaker",
    ],
    "Ranger": [
        "Hunter",
        "Beast Master",
        "Gloom Stalker",
        "Horizon Walker",
        "Monster Slayer",
        "Fey Wanderer",
        "Swarmkeeper",
        "Drakewarden",
    ],
    "Rogue": [
        "Thief",
        "Assassin",
        "Arcane Trickster",
        "Inquisitive",
        "Mastermind",
        "Scout",
        "Swashbuckler",
        "Phantom",
        "Soulknife",
    ],
    "Sorcerer": [
        "Draconic Bloodline",
        "Wild Magic",
        "Divine Soul",
        "Shadow Magic",
        "Storm Sorcery",
        "Aberrant Mind",
        "Clockwork Soul",
    ],
    "Warlock": [
        "The Archfey",
        "The Fiend",
        "The Great Old One",
        "The Undying",
        "The Celestial",
        "The Hexblade",
        "The Fathomless",
        "The Genie",
        "The Undead",
    ],
    "Wizard": [
        "School of Abjuration",
        "School of Conjuration",
        "School of Divination",
        "School of Enchantment",
        "School of Evocation",
        "School of Illusion",
        "School of Necromancy",
        "School of Transmutation",
        "Bladesinging",
        "War Magic",
        "Chronurgy Magic",
        "Graviturgy Magic",
        "Order of Scribes",
    ],
}

# ==========================================
# 2024 Ruleset (5.5e)
# ==========================================
SPECIES_2024 = [
    "Aasimar",
    "Dragonborn",
    "Dwarf",
    "Elf",
    "Gnome",
    "Goliath",
    "Halfling",
    "Human",
    "Orc",
    "Tiefling",
]

CLASSES_2024 = [
    "Barbarian",
    "Bard",
    "Cleric",
    "Druid",
    "Fighter",
    "Monk",
    "Paladin",
    "Ranger",
    "Rogue",
    "Sorcerer",
    "Warlock",
    "Wizard",
]

BACKGROUNDS_2024 = [
    "Acolyte",
    "Artisan",
    "Charlatan",
    "Criminal",
    "Entertainer",
    "Farmer",
    "Guard",
    "Guide",
    "Hermit",
    "Merchant",
    "Noble",
    "Sage",
    "Sailor",
    "Scribe",
    "Soldier",
    "Wayfarer",
]

SUBCLASSES_2024 = {
    "Barbarian": [
        "Path of the Berserker",
        "Path of the Wild Heart",
        "Path of the World Tree",
        "Path of the Zealot",
    ],
    "Bard": [
        "College of Dance",
        "College of Glamour",
        "College of Lore",
        "College of Valor",
    ],
    "Cleric": ["Life Domain", "Light Domain", "Trickery Domain", "War Domain"],
    "Druid": [
        "Circle of the Land",
        "Circle of the Moon",
        "Circle of the Sea",
        "Circle of the Stars",
    ],
    "Fighter": ["Battle Master", "Champion", "Eldritch Knight", "Psi Warrior"],
    "Monk": [
        "Warrior of Mercy",
        "Warrior of Shadow",
        "Warrior of the Elements",
        "Warrior of the Open Hand",
    ],
    "Paladin": [
        "Oath of Devotion",
        "Oath of Glory",
        "Oath of the Ancients",
        "Oath of Vengeance",
    ],
    "Ranger": ["Beast Master", "Fey Wanderer", "Gloom Stalker", "Hunter"],
    "Rogue": ["Arcane Trickster", "Assassin", "Soulknife", "Thief"],
    "Sorcerer": [
        "Aberrant Sorcery",
        "Clockwork Sorcery",
        "Draconic Sorcery",
        "Wild Magic",
    ],
    "Warlock": [
        "Archfey Patron",
        "Celestial Patron",
        "Fiend Patron",
        "Great Old One Patron",
    ],
    "Wizard": ["Abjurer", "Diviner", "Evoker", "Illusionist"],
}

WEAPON_MASTERIES_2024 = [
    "Cleave",
    "Graze",
    "Nick",
    "Push",
    "Sap",
    "Slow",
    "Topple",
    "Vex",
]

# PDF Positioning (Constants for drawing on the template)
PDF_PORTRAIT_X = 45
PDF_PORTRAIT_Y = 450
PDF_PORTRAIT_WIDTH = 175
PDF_PORTRAIT_HEIGHT = 180
