name: Phyrexian Forge Frontend CI

on:
  push:
    branches: [ dev, main, "feat/*", "feature/*" ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    name: Run Angular Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Run Jest Tests
        run: npm run test
