name: Rebase Enforcer

on:
  pull_request:
    branches: [ "*" ]

jobs:
  enforce-rebase:
    name: rebase-check
    runs-on: ubuntu-latest
    steps:
      - name: Dummy check for rebase rule
        run: echo "This check only exists to satisfy GitHub's requirement for the 'Require branches to be up to date' rule."
